fix(k8s-wait-job): embed it (#72)

diff --git a/autodevops-create-db-secret/action.yml b/autodevops-create-db-secret/action.yml
--- a/autodevops-create-db-secret/action.yml
+++ b/autodevops-create-db-secret/action.yml
@@ -79,6 +79,27 @@ runs:
         kubectl apply --namespace=${{ steps.namespace.outputs.result }} -f create-db-secret.yml
 
     - name: Wait for job to complete
-      runs-on: ghcr.io/socialgouv/docker/kubectl
       shell: bash
-      run: k8s-wait-job ${{ steps.namespace.outputs.result }} create-db-secret
+      run: |
+        # k8s-wait-job ${{ steps.namespace.outputs.result }} create-db-secret
+        K8S_NAMESPACE=${{ steps.namespace.outputs.result }}
+        JOB_NAME=create-db-secret
+        JOB="job/$JOB_NAME"
+        retval_complete=1
+        retval_failed=1
+        while [[ $retval_complete -ne 0 ]] && [[ $retval_failed -ne 0 ]]; do
+          sleep 2
+          output=$(timeout 2s kubectl -n $K8S_NAMESPACE wait --for=condition=complete $JOB --timeout=0 2>&1)
+          retval_complete=$?
+          output=$(timeout 2s kubectl -n $K8S_NAMESPACE wait --for=condition=failed $JOB --timeout=0 2>&1)
+          retval_failed=$?
+          wait
+        done
+        if [ $retval_failed -eq 0 ]; then
+          echo "$JOB failed"
+          exit 1
+        else
+          echo "$JOB complete"
+        fi
+
+
