fix

diff --git a/.github/workflows/k8s-manifests-debug-test.yaml b/.github/workflows/k8s-manifests-debug-test.yaml
--- a/.github/workflows/k8s-manifests-debug-test.yaml
+++ b/.github/workflows/k8s-manifests-debug-test.yaml
@@ -12,49 +12,51 @@ jobs:
         with:
           path: ./k8s-manifests-debug/sample.yml
           token: ${{ secrets.GITHUB_TOKEN }}
+      - name: "json output exist"
+        run: |
+          [[ -n "${{ steps.manifests-debug.outputs.json }}" ]] || (echo "No json" && exit 1)
+
       - name: "markdown output exist"
         run: |
           [[ -n "${{ steps.manifests-debug.outputs.markdown }}" ]] || (echo "No markdown" && exit 1)
 
-      - name: "text output exist"
+      - name: "text output is correct"
         run: |
-          [[ -n "${{ steps.manifests-debug.outputs.text }}" ]] || (echo "No text" && exit 1)
+          TEXT='### Ingresses
 
-      - name: "json output is correct"
-        run: |
-          JSON='{
-            isProduction: false,
-            manifests: [
-              {
-                kind: Deployment,
-                name: nginx-deployment
-              },
-              {
-                kind: Service,
-                name: nginx
-              },
-              {
-                kind: Ingress,
-                name: example-ingress
-              }
-            ],
-            hosts: [
-              hello-world.info
-            ],
-            images: [
-              nginx:1.14.2
-            ]
-          }'
+          - 🚀 https://hello-world.info
 
-          if [[ "${JSON}" != "${{ steps.manifests-debug.outputs.json }}" ]]; then
+          ### Docker images
+
+          - 📦 docker pull nginx:1.14.2
+
+          ### Debug
+
+          #### 📕 Loki logs for namespace undefined:
+
+          https://grafana.fabrique.social.gouv.fr/explore?orgId=1&left=%5B%22now-6h%22,%22now%22,%22Loki-tail%22,%7B%22expr%22:%22%7Bnamespace%3D%5C%22undefined%5C%22%7D%22%7D%5D
+
+          #### 📈 Pods monitoring for namespace undefined:
+
+          https://grafana.fabrique.social.gouv.fr/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&refresh=10s&var-datasource=default&var-cluster=dev2&var-namespace=undefined
+
+          #### 📈 Workloads monitoring for namespace undefined:
+
+          https://grafana.fabrique.social.gouv.fr/d/a87fb0d919ec0ea5f6543124e16c42a5/kubernetes-compute-resources-namespace-workloads?orgId=1&refresh=10s&var-datasource=default&var-cluster=dev2&var-namespace=undefined&var-type=deployment
+
+          #### 👮‍♂️ Rancher project undefined:
+
+          https://rancher.fabrique.social.gouv.fr/p//workloads'
+
+          if [[ "${TEXT}" != "${{ steps.manifests-debug.outputs.text }}" ]]; then
             echo "------------------"
-            echo "Invalid JSON"
+            echo "Invalid TEXT"
             echo "-"
             echo "Expected:"
-            echo "${JSON}"
+            echo "${TEXT}"
             echo "---"
             echo "Actual:"
-            echo "${{ steps.manifests-debug.outputs.json }}"
+            echo "${{ steps.manifests-debug.outputs.text }}"
             echo "------------------"
             exit 1
           fi
